import { ListStatus } from '@/types/list';

type StepDetail = {
  name: ListStatus;
  date?: Date | null;
};

export const generateSteps = (steps: StepDetail[]): string[] => {
  return steps.map(({ name, date }) => {
    return date ? `${name} - ${date.toLocaleDateString()}` : name;
  });
};

export const statusSteps: ListStatus[] = [
  'aguardando pagamento',
  'pagamento aprovado',
  'aguardando protocolar',
  'decisão judicial',
  'spc',
  'boa vista',
  'cenprot sp',
  'cenprot br',
  'quod',
  'serasa',
  'finalizada',
];

export const diligences = [
  'Ajuizamento Físico',
  'Cancelamendo de protocolog de título protesto',
  'Cópia inicial',
  'Cópia de Sentença',
  'Cópia de FLS ...AS...',
  'Cópia documento de retomada de bem',
  'Cópia integral',
  'Despacho',
  'Distribuição',
  'Distribuir Carta Precatória - Física',
  'Preposto audiência judicial',
  'Preposto audiência extrajudicial',
  'Protocolo eletronico',
  'Protocolo de minuta de acordo',
  'Protocolo de título de protesto',
  'Protocolo físico',
  'Retirada de documento',
  'Retirar CP',
];

export const holidays = [
  '2024-01-01', // New Year's Day
  '2024-02-12', // Carnival Monday
  '2024-02-13', // Carnival Tuesday
  '2024-03-29', // Good Friday
  '2024-04-21', // Tiradentes' Day
  '2024-05-01', // Labor Day
  '2024-05-30', // Corpus Christi
  '2024-09-07', // Independence Day
  '2024-10-12', // Our Lady of Aparecida
  '2024-11-02', // All Souls' Day
  '2024-11-15', // Republic Day
  '2024-12-25', // Christmas Day
];

export const processing = [
  'Processo Físico',
  'Processo Eletrônico',
  // "Solicitar Certidão"
];

export const physicalDelivery = ['Sim', 'Não'];

export const generatediligence = ['Sim', 'Não'];

export const clients = [
  { id: 1, nome: 'Aeroportos Federais do Brasil' },
  { id: 2, nome: 'Banco Aurora Investimentos' },
  { id: 3, nome: 'Banco Capital Real' },
  { id: 4, nome: 'Banco Cidade Verde' },
  { id: 5, nome: 'Banco Estrela do Sul' },
  { id: 6, nome: 'Banco União Financeiro' },
  { id: 7, nome: 'Companhia de Água e Saneamento Nacional' },
  { id: 8, nome: 'Eletricidade do Vale Verde' },
  { id: 9, nome: 'Eletricidade Luminar' },
  { id: 10, nome: 'Energia Estatal Nacional' },
  { id: 11, nome: 'Energia Renovável Eólica' },
  { id: 12, nome: 'Energia Solaris' },
  { id: 13, nome: 'Ferrovias Pátria' },
  { id: 14, nome: 'Geração Energética Sustentável' },
  { id: 15, nome: 'PetroBrasil' },
];

export const typeterm = [
  { id: 1, nome: 'Parte' },
  { id: 2, nome: 'CPF/CNPJ' },
  { id: 3, nome: 'Nº do Processo' },
  { id: 4, nome: 'Nome/razão social' },
];

export const tipocertidao = [
  { id: 1, nome: 'CND Municipal', valor: 'CND Municipal' },
  { id: 2, nome: 'CND Estadual', valor: 'CND Estadual' },
  { id: 3, nome: 'CND Receita Federal', valor: 'CND Receita Federal' },
  { id: 4, nome: 'CND FGTS', valor: 'CND FGTS' },
  { id: 5, nome: 'CND INSS', valor: 'CND INSS' },
  { id: 6, nome: 'CND de Débitos Trabalhistas', valor: 'CND de Débitos Trabalhistas' },
  { id: 7, nome: 'CND de tributos mobiliários', valor: 'CND de tributos mobiliários' },
  { id: 8, nome: 'CND de tributos imobiliários', valor: 'CND de tributos imobiliários' },
];

export const periodos = [
  { id: 1, nome: 'Quinzenal', valor: 'Quinzenal' },
  { id: 2, nome: 'Mensal', valor: 'Mensal' },
  { id: 3, nome: 'Trimestral', valor: 'Trimestral' },
  { id: 4, nome: 'Semestral', valor: 'Semestral' },
];

export const modelo = [
  { id: 1, nome: 'Eventual', valor: 'Eventual' },
  { id: 2, nome: 'Recorrente', valor: 'Recorrente' },
];

export const diarycolumns = [
  { id: 1, nome: 'DJ AC' },
  { id: 2, nome: 'DJ AL' },
  { id: 3, nome: 'DJ AM' },
  { id: 4, nome: 'DJ AP' },
  { id: 5, nome: 'DJ BA' },
  { id: 6, nome: 'DJ CE' },
  { id: 7, nome: 'DJ ES' },
  { id: 8, nome: 'DJ GO' },
  { id: 9, nome: 'DJ MG' },
  { id: 10, nome: 'DJ MS' },
  { id: 11, nome: 'DJ MT' },
  { id: 12, nome: 'DJ PA' },
  { id: 13, nome: 'DJ PB' },
  { id: 14, nome: 'DJ PE' },
  { id: 15, nome: 'DJ PI' },
  { id: 16, nome: 'DJ PR' },
  { id: 17, nome: 'DJ RJ' },
  { id: 18, nome: 'DJ RN' },
  { id: 19, nome: 'DJ RO' },
  { id: 20, nome: 'DJ RR' },
  { id: 21, nome: 'DJ RS' },
  { id: 22, nome: 'DJ SC' },
  { id: 23, nome: 'DJ SE' },
];

export const ufs = [
  { id: 1, nome: 'AC', estado: 'Acre' },
  { id: 2, nome: 'AL', estado: 'Alagoas' },
  { id: 3, nome: 'AP', estado: 'Amapá' },
  { id: 4, nome: 'AM', estado: 'Amazonas' },
  { id: 5, nome: 'BA', estado: 'Bahia' },
  { id: 6, nome: 'CE', estado: 'Ceará' },
  { id: 7, nome: 'DF', estado: 'Distrito Federal' },
  { id: 8, nome: 'ES', estado: 'Espírito Santo' },
  { id: 9, nome: 'GO', estado: 'Goiás' },
  { id: 10, nome: 'MA', estado: 'Maranhão' },
  { id: 11, nome: 'MT', estado: 'Mato Grosso' },
  { id: 12, nome: 'MS', estado: 'Mato Grosso do Sul' },
  { id: 13, nome: 'MG', estado: 'Minas Gerais' },
  { id: 14, nome: 'PA', estado: 'Pará' },
  { id: 15, nome: 'PB', estado: 'Paraíba' },
  { id: 16, nome: 'PR', estado: 'Paraná' },
  { id: 17, nome: 'PE', estado: 'Pernambuco' },
  { id: 18, nome: 'PI', estado: 'Piauí' },
  { id: 19, nome: 'RJ', estado: 'Rio de Janeiro' },
  { id: 20, nome: 'RN', estado: 'Rio Grande do Norte' },
  { id: 21, nome: 'RS', estado: 'Rio Grande do Sul' },
  { id: 22, nome: 'RO', estado: 'Rondônia' },
  { id: 23, nome: 'RR', estado: 'Roraima' },
  { id: 24, nome: 'SC', estado: 'Santa Catarina' },
  { id: 25, nome: 'SP', estado: 'São Paulo' },
  { id: 26, nome: 'SE', estado: 'Sergipe' },
  { id: 27, nome: 'TO', estado: 'Tocantins' },
];

export const entregaFisico = [
  { id: 1, nome: 'Processo Físico', valor: 'Sim' },
  { id: 2, nome: 'Processo Eletrônico', valor: 'Não' },
];

export const statusAtivo = [
  { id: 1, nome: 'Ativo', valor: 'ativo' },
  { id: 2, nome: 'Encerrado', valor: 'encerrado' },
];

export const courtsystem = [
  { id: 11, nome: 'e-Proc', sigla: 'e-Proc' },
  { id: 12, nome: 'e-Proc CNJ', sigla: 'e-Proc CNJ' },
  { id: 13, nome: 'e-Proc Nacional', sigla: 'e-Proc Nacional' },
  { id: 14, nome: 'e-Proc TRF2', sigla: 'e-Proc TRF2' },
  { id: 15, nome: 'e-SAJ', sigla: 'e-SAJ' },
  { id: 16, nome: 'e-SAJ TJBA', sigla: 'e-SAJ TJBA' },
  { id: 17, nome: 'e-SAJ TJMG', sigla: 'e-SAJ TJMG' },
  { id: 18, nome: 'e-SAJ TJRJ', sigla: 'e-SAJ TJRJ' },
  { id: 19, nome: 'e-SAJ TJRS', sigla: 'e-SAJ TJRS' },
  { id: 20, nome: 'e-SAJ TJSP', sigla: 'e-SAJ TJSP' },
  { id: 21, nome: 'e-Themis', sigla: 'e-Themis' },
  { id: 22, nome: 'PJe', sigla: 'PJe' },
  { id: 23, nome: 'PJe-CNJ', sigla: 'PJe-CNJ' },
  { id: 24, nome: 'PJe-JT', sigla: 'PJe-JT' },
  { id: 25, nome: 'Projudi', sigla: 'Projudi' },
  { id: 26, nome: 'Projudi TJPR', sigla: 'Projudi TJPR' },
  { id: 27, nome: 'SAJ', sigla: 'SAJ' },
  { id: 28, nome: 'SEI', sigla: 'SEI' },
  { id: 29, nome: 'SISCOM', sigla: 'SISCOM' },
  { id: 30, nome: 'TJ Digital', sigla: 'TJ Digital' },
];

export const vara = [
  { id: 1, nome: 'Parte' },
  { id: 2, nome: 'CPF/CNPJ' },
  { id: 3, nome: 'Nº do Processo' },
  { id: 4, nome: 'Nome/razão social' },
  { id: 5, nome: 'Vara de Família e Sucessões' },
  { id: 6, nome: 'Vara Cível' },
  { id: 7, nome: 'Vara Criminal' },
  { id: 8, nome: 'Vara de Fazenda Pública' },
  { id: 9, nome: 'Vara da Infância e Juventude' },
  { id: 10, nome: 'Vara de Execuções Penais' },
  { id: 11, nome: 'Vara de Registros Públicos' },
  { id: 12, nome: 'Vara da Fazenda Pública' },
  { id: 13, nome: 'Vara de Trabalho' },
  { id: 14, nome: 'Vara da Justiça Federal' },
];

export const validacoes = [
  { id: 1, nome: 'Todos', value: '' },
  { id: 2, nome: 'Pendente', value: 'Pendente' },
  { id: 3, nome: 'Concluída', value: 'Concluída' },
  { id: 4, nome: 'Aceita', value: 'Aceita' },
];

export const classification = [
  { id: 1, nome: 'Acórdão' },
  { id: 2, nome: 'Agravo de Instrumento' },
  { id: 3, nome: 'Agravo em Recurso Especial/ Recurso Extraordinário' },
  { id: 4, nome: 'Agravo Interno' },
  { id: 5, nome: 'Apelação' },
  { id: 6, nome: 'Audiência trabalhista' },
  { id: 7, nome: 'Comprovar cumprimento de obrigação de fazer/não fazer' },
  { id: 8, nome: 'Conciliação' },
  { id: 9, nome: 'Conciliação, Instrução e Julgamento' },
  { id: 10, nome: 'Contrarrazões de Apelação' },
  { id: 11, nome: 'Contrarrazões de Recurso Especial' },
  { id: 12, nome: 'Contrarrazões de Recurso Inominado' },
  { id: 13, nome: 'Custas' },
  { id: 14, nome: 'Efetuar pagamento' },
  { id: 15, nome: 'Efetuar pagamento de honorários periciais' },
  { id: 16, nome: 'Embargos à execução' },
  { id: 17, nome: 'Embargos de Declaração' },
  { id: 18, nome: 'Especificar provas' },
  { id: 19, nome: 'Fim de vista' },
  { id: 20, nome: 'Impugnação' },
  { id: 21, nome: 'Impugnação à contestação' },
  { id: 22, nome: 'Impugnação aos embargos à execução' },
  { id: 23, nome: 'Impugnar cálculos' },
  { id: 24, nome: 'Impugnar cálculos trabalhistas' },
  { id: 25, nome: 'Inclusão de Resultado de Sentença no Portal' },
  { id: 26, nome: 'Indicar bens à penhora' },
  { id: 27, nome: 'Juntada 1º Grau' },
  { id: 28, nome: 'Juntar documentos' },
  { id: 29, nome: 'Juntar planilha de cálculos atualizada' },
  { id: 30, nome: 'Manifestação de laudo pericial' },
  { id: 31, nome: 'Manifestar 1º Grau' },
  { id: 32, nome: 'Manifestar 2º Grau' },
  { id: 33, nome: 'Manifestar fim da dilação' },
  { id: 34, nome: 'Manifestar interesse em audiência de conciliação' },
  { id: 35, nome: 'Manifestar oposição ao julgamento virtual' },
  { id: 36, nome: 'Manifestar sob pena' },
  { id: 37, nome: 'Manifestar sobre bloqueio online' },
  { id: 38, nome: 'Manifestar sobre despacho' },
  { id: 39, nome: 'Manifestar sobre despacho trabalhista' },
  { id: 40, nome: 'Manifestar sobre embargos de declaração' },
  { id: 41, nome: 'Manifestar sobre mandado/AR' },
  { id: 42, nome: 'PA - Procedimento Administrativo' },
  { id: 43, nome: 'Providenciar novo endereço' },
  { id: 44, nome: 'Quesitos/ Indicar assistente técnico' },
  { id: 45, nome: 'Recolher custas finais' },
  { id: 46, nome: 'Recolher custas sob pena' },
  { id: 47, nome: 'Recolher/complementar preparo' },
  { id: 48, nome: 'Recurso Especial' },
  { id: 49, nome: 'Recurso Inominado' },
  { id: 50, nome: 'Regularizar a representação processual' },
  { id: 51, nome: 'Requerer o que entender de direito' },
  { id: 52, nome: 'Retirar documentos' },
  { id: 53, nome: 'Retirar mandado de pagamento' },
  { id: 54, nome: 'Sentença cível extinção' },
  { id: 55, nome: 'Sessão de Julgamento' },
  { id: 56, nome: 'Verificar desarquivamento' },
];

export const listIdentificacao = [
  { id: 1, nome: 'Todos', value: '' },
  { id: 2, nome: 'Identificada', value: 'Identificada' },
  { id: 3, nome: 'Não Identificada', value: 'Não Identificada' },
];

export const listOrigemCaptura = [
  { id: 1, nome: 'Todos', value: '' },
  { id: 2, nome: 'Diário', value: 'Diário' },
  { id: 3, nome: 'Eletrônico', value: 'Eletrônico' },
  { id: 4, nome: 'Distribuição', value: 'Distribuição' },
  { id: 5, nome: 'Andamento', value: 'Andamento' },
];

export const listTribunalCategoria = [
  { id: 1, nome: 'Tribunal de Justiça' },
  { id: 2, nome: 'Tribunal Eleitoral' },
  { id: 3, nome: 'Tribunal Federal' },
  { id: 4, nome: 'Tribunal Trabalhista' },
];

export const listDiariosJudiciarios = [
  {
    id: 1,
    idUF: 1,
    idTribCateg: 1,
    nome: 'TJAC',
    descricao: 'D.O. Acre - TRIBUNAL DE JUSTIÇA',
  },
  { id: 2, idUF: 1, idTribCateg: 2, nome: 'TREAC', descricao: 'DJE TRE - AC' },
  {
    id: 3,
    idUF: 1,
    idTribCateg: 3,
    nome: 'JFAC',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 4,
    idUF: 1,
    idTribCateg: 4,
    nome: 'TRT14',
    descricao: 'D.O. Rondônia - TRT',
  },

  {
    id: 5,
    idUF: 2,
    idTribCateg: 1,
    nome: 'TJAL',
    descricao: 'D.O. Alagoas - TRIBUNAL DE JUSTIÇA - Caderno 1 - Jurisdicional e Administrativo',
  },
  {
    id: 6,
    idUF: 2,
    idTribCateg: 1,
    nome: 'TJAL',
    descricao: 'D.O. Alagoas - TRIBUNAL DE JUSTIÇA - Caderno 2 - Jurisdicional - Primeiro Grau',
  },
  { id: 7, idUF: 2, idTribCateg: 2, nome: 'TREAL', descricao: 'DJE TRE - AL' },
  {
    id: 8,
    idUF: 2,
    idTribCateg: 3,
    nome: 'JFAL',
    descricao: 'D.J.DF SEC II - TRF DA 5 REG',
  },
  {
    id: 9,
    idUF: 2,
    idTribCateg: 3,
    nome: 'JFAL',
    descricao: 'D.O. Alagoas - SEC JUD FEDERAL',
  },
  {
    id: 10,
    idUF: 2,
    idTribCateg: 3,
    nome: 'JFAL',
    descricao: 'TRF DA 5 REG (DJEN)',
  },
  {
    id: 11,
    idUF: 2,
    idTribCateg: 4,
    nome: 'TRT19',
    descricao: 'D.O. Alagoas - TRT',
  },

  {
    id: 12,
    idUF: 4,
    idTribCateg: 1,
    nome: 'TJAM',
    descricao: 'D.O. AM - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 13,
    idUF: 4,
    idTribCateg: 1,
    nome: 'TJAM',
    descricao: 'D.O. Amazonas - TRIBUNAL DE JUSTIÇA - Caderno 1 - Administrativo',
  },
  {
    id: 14,
    idUF: 4,
    idTribCateg: 1,
    nome: 'TJAM',
    descricao: 'D.O. Amazonas - TRIBUNAL DE JUSTIÇA - Caderno 2 - Judiciário - Capital',
  },
  {
    id: 15,
    idUF: 4,
    idTribCateg: 1,
    nome: 'TJAM',
    descricao: 'D.O. Amazonas - TRIBUNAL DE JUSTIÇA - Caderno 3 - Judiciário - Interior',
  },
  {
    id: 16,
    idUF: 4,
    idTribCateg: 1,
    nome: 'TJAM',
    descricao:
      'D.O. Amazonas - TRIBUNAL DE JUSTIÇA - Caderno 4 - Judiciário - Distribuição e Eliminação de Processos Judicias',
  },
  { id: 17, idUF: 4, idTribCateg: 2, nome: 'TREAM', descricao: 'DJE TRE - AM' },
  {
    id: 18,
    idUF: 4,
    idTribCateg: 3,
    nome: 'JFAM',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 19,
    idUF: 4,
    idTribCateg: 4,
    nome: 'TRT11',
    descricao: 'D. O. AM TRT - JT',
  },

  {
    id: 20,
    idUF: 3,
    idTribCateg: 1,
    nome: 'TJAP',
    descricao: 'D.O. Amapá - TRIBUNAL DE JUSTIÇA',
  },
  {
    id: 21,
    idUF: 3,
    idTribCateg: 1,
    nome: 'TJAP',
    descricao: 'D.O. Amapá - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  { id: 22, idUF: 3, idTribCateg: 2, nome: 'TREAP', descricao: 'DJE TRE - AP' },
  {
    id: 23,
    idUF: 3,
    idTribCateg: 3,
    nome: 'JFAP',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 24,
    idUF: 3,
    idTribCateg: 4,
    nome: 'TRT08',
    descricao: 'D.O. PARA TRT',
  },

  {
    id: 25,
    idUF: 5,
    idTribCateg: 1,
    nome: 'TJBA',
    descricao: 'D.O. BAHIA - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 26,
    idUF: 5,
    idTribCateg: 1,
    nome: 'TJBA',
    descricao: 'DJE TJ BA - CAD 1 - ADMINISTRATIVO',
  },
  {
    id: 27,
    idUF: 5,
    idTribCateg: 1,
    nome: 'TJBA',
    descricao: 'DJE TJ BA - CAD 2 - ORGAOS JUDICANTES DE 2 GRAU',
  },
  {
    id: 28,
    idUF: 5,
    idTribCateg: 1,
    nome: 'TJBA',
    descricao: 'DJE TJ BA - CAD 3 - ENTRANCIA FINAL',
  },
  {
    id: 29,
    idUF: 5,
    idTribCateg: 1,
    nome: 'TJBA',
    descricao: 'DJE TJ BA - CAD 4 - ENTRANCIA INTERMEDIARIA',
  },
  {
    id: 30,
    idUF: 5,
    idTribCateg: 1,
    nome: 'TJBA',
    descricao: 'DJE TJ BA - CAD 5 - ENTRANCIA INICIAL',
  },
  { id: 31, idUF: 5, idTribCateg: 2, nome: 'TREBA', descricao: 'DJE TRE - BA' },
  {
    id: 32,
    idUF: 5,
    idTribCateg: 3,
    nome: 'JFBA',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 33,
    idUF: 5,
    idTribCateg: 4,
    nome: 'TRT05',
    descricao: 'D.O. BAHIA - TRT 5º REGIÃO (CAPITAL 1)',
  },

  {
    id: 34,
    idUF: 6,
    idTribCateg: 1,
    nome: 'TJCE',
    descricao: 'D.O. CEARÁ - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 35,
    idUF: 6,
    idTribCateg: 1,
    nome: 'TJCE',
    descricao: 'DJE TJ CE - PARTE 1',
  },
  {
    id: 36,
    idUF: 6,
    idTribCateg: 1,
    nome: 'TJCE',
    descricao: 'DJE TJ CE - PARTE 2',
  },
  {
    id: 37,
    idUF: 6,
    idTribCateg: 1,
    nome: 'TJCE',
    descricao: 'DJE TJ CE - PARTE 3',
  },
  {
    id: 38,
    idUF: 6,
    idTribCateg: 1,
    nome: 'TJCE',
    descricao: 'DJE TJ CE - PARTE 4',
  },
  { id: 39, idUF: 6, idTribCateg: 2, nome: 'TRECE', descricao: 'DJE TRE - CE' },
  {
    id: 40,
    idUF: 6,
    idTribCateg: 3,
    nome: 'JFCE',
    descricao: 'TRF DA 5 REG (DJEN)',
  },
  {
    id: 41,
    idUF: 6,
    idTribCateg: 4,
    nome: 'TRT07',
    descricao: 'D.O. CEARÁ - TRT',
  },

  {
    id: 42,
    idUF: 7,
    idTribCateg: 1,
    nome: 'TJDF',
    descricao: 'D.O. DISTRITO FEDERAL - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 43,
    idUF: 7,
    idTribCateg: 1,
    nome: 'TJDF',
    descricao: 'DJE TJ DF - PARTE 1',
  },
  {
    id: 44,
    idUF: 7,
    idTribCateg: 1,
    nome: 'TJDF',
    descricao: 'DJE TJ DF - PARTE 2',
  },
  {
    id: 45,
    idUF: 7,
    idTribCateg: 1,
    nome: 'TJDF',
    descricao: 'DJE TJ DF - PARTE 3',
  },
  {
    id: 46,
    idUF: 7,
    idTribCateg: 1,
    nome: 'TJDF',
    descricao: 'DJE TJ DF - PARTE 4',
  },
  { id: 47, idUF: 7, idTribCateg: 2, nome: 'TREDF', descricao: 'DJE TRE - DF' },
  {
    id: 48,
    idUF: 7,
    idTribCateg: 3,
    nome: 'JFDF',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 49,
    idUF: 7,
    idTribCateg: 4,
    nome: 'TRT10',
    descricao: 'D.O. DISTRITO FEDERAL - TRT',
  },

  {
    id: 50,
    idUF: 8,
    idTribCateg: 1,
    nome: 'TJES',
    descricao: 'D.O. ESPÍRITO SANTO - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 51,
    idUF: 8,
    idTribCateg: 1,
    nome: 'TJES',
    descricao: 'DJE TJ ES - PARTE 1',
  },
  {
    id: 52,
    idUF: 8,
    idTribCateg: 1,
    nome: 'TJES',
    descricao: 'DJE TJ ES - PARTE 2',
  },
  {
    id: 53,
    idUF: 8,
    idTribCateg: 1,
    nome: 'TJES',
    descricao: 'DJE TJ ES - PARTE 3',
  },
  { id: 54, idUF: 8, idTribCateg: 2, nome: 'TREES', descricao: 'DJE TRE - ES' },
  {
    id: 55,
    idUF: 8,
    idTribCateg: 3,
    nome: 'JFES',
    descricao: 'TRF DA 2 REG (DJEN)',
  },
  {
    id: 56,
    idUF: 8,
    idTribCateg: 4,
    nome: 'TRT17',
    descricao: 'D.O. ESPÍRITO SANTO - TRT',
  },

  {
    id: 57,
    idUF: 9,
    idTribCateg: 1,
    nome: 'TJGO',
    descricao: 'D.O. GOIÁS - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 58,
    idUF: 9,
    idTribCateg: 1,
    nome: 'TJGO',
    descricao: 'DJE TJ GO - PARTE 1',
  },
  {
    id: 59,
    idUF: 9,
    idTribCateg: 1,
    nome: 'TJGO',
    descricao: 'DJE TJ GO - PARTE 2',
  },
  { id: 60, idUF: 9, idTribCateg: 2, nome: 'TREGO', descricao: 'DJE TRE - GO' },
  {
    id: 61,
    idUF: 9,
    idTribCateg: 3,
    nome: 'JFGO',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 62,
    idUF: 9,
    idTribCateg: 4,
    nome: 'TRT18',
    descricao: 'D.O. GOIÁS - TRT',
  },

  {
    id: 63,
    idUF: 10,
    idTribCateg: 1,
    nome: 'TJMA',
    descricao: 'D.O. MARANHÃO - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 64,
    idUF: 10,
    idTribCateg: 1,
    nome: 'TJMA',
    descricao: 'DJE TJ MA - PARTE 1',
  },
  {
    id: 65,
    idUF: 10,
    idTribCateg: 1,
    nome: 'TJMA',
    descricao: 'DJE TJ MA - PARTE 2',
  },
  {
    id: 66,
    idUF: 10,
    idTribCateg: 2,
    nome: 'TREMA',
    descricao: 'DJE TRE - MA',
  },
  {
    id: 67,
    idUF: 10,
    idTribCateg: 3,
    nome: 'JFMA',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 68,
    idUF: 10,
    idTribCateg: 4,
    nome: 'TRT16',
    descricao: 'D.O. MARANHÃO - TRT',
  },

  {
    id: 69,
    idUF: 11,
    idTribCateg: 1,
    nome: 'TJMT',
    descricao: 'D.O. MATO GROSSO - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 70,
    idUF: 11,
    idTribCateg: 1,
    nome: 'TJMT',
    descricao: 'DJE TJ MT - PARTE 1',
  },
  {
    id: 71,
    idUF: 11,
    idTribCateg: 1,
    nome: 'TJMT',
    descricao: 'DJE TJ MT - PARTE 2',
  },
  {
    id: 72,
    idUF: 11,
    idTribCateg: 1,
    nome: 'TJMT',
    descricao: 'DJE TJ MT - PARTE 3',
  },
  {
    id: 73,
    idUF: 11,
    idTribCateg: 2,
    nome: 'TREMT',
    descricao: 'DJE TRE - MT',
  },
  {
    id: 74,
    idUF: 11,
    idTribCateg: 3,
    nome: 'JFMT',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 75,
    idUF: 11,
    idTribCateg: 4,
    nome: 'TRT23',
    descricao: 'D.O. MATO GROSSO - TRT',
  },

  {
    id: 76,
    idUF: 12,
    idTribCateg: 1,
    nome: 'TJMS',
    descricao: 'D.O. MATO GROSSO DO SUL - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 77,
    idUF: 12,
    idTribCateg: 1,
    nome: 'TJMS',
    descricao: 'DJE TJ MS - PARTE 1',
  },
  {
    id: 78,
    idUF: 12,
    idTribCateg: 1,
    nome: 'TJMS',
    descricao: 'DJE TJ MS - PARTE 2',
  },
  {
    id: 79,
    idUF: 12,
    idTribCateg: 2,
    nome: 'TREMS',
    descricao: 'DJE TRE - MS',
  },
  {
    id: 80,
    idUF: 12,
    idTribCateg: 3,
    nome: 'JFMS',
    descricao: 'TRF DA 3 REG (DJEN)',
  },
  {
    id: 81,
    idUF: 12,
    idTribCateg: 4,
    nome: 'TRT24',
    descricao: 'D.O. MATO GROSSO DO SUL - TRT',
  },

  {
    id: 82,
    idUF: 13,
    idTribCateg: 1,
    nome: 'TJMG',
    descricao: 'D.O. MINAS GERAIS - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 83,
    idUF: 13,
    idTribCateg: 1,
    nome: 'TJMG',
    descricao: 'DJE TJ MG - PARTE 1',
  },
  {
    id: 84,
    idUF: 13,
    idTribCateg: 1,
    nome: 'TJMG',
    descricao: 'DJE TJ MG - PARTE 2',
  },
  {
    id: 85,
    idUF: 13,
    idTribCateg: 2,
    nome: 'TREMG',
    descricao: 'DJE TRE - MG',
  },
  {
    id: 86,
    idUF: 13,
    idTribCateg: 3,
    nome: 'JFMG',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 87,
    idUF: 13,
    idTribCateg: 4,
    nome: 'TRT25',
    descricao: 'D.O. MINAS GERAIS - TRT',
  },

  {
    id: 88,
    idUF: 14,
    idTribCateg: 1,
    nome: 'TJPA',
    descricao: 'D.O. PARA TJ (CAD 1)',
  },
  {
    id: 89,
    idUF: 14,
    idTribCateg: 1,
    nome: 'TJPA',
    descricao: 'D.O. PARA TJ (DJEN)',
  },
  {
    id: 92,
    idUF: 14,
    idTribCateg: 2,
    nome: 'TREPA',
    descricao: 'DJE TRE - PA',
  },
  {
    id: 93,
    idUF: 14,
    idTribCateg: 3,
    nome: 'JFPA',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 94,
    idUF: 14,
    idTribCateg: 4,
    nome: 'TRT08',
    descricao: 'D.O. PARA - TRT',
  },

  {
    id: 95,
    idUF: 15,
    idTribCateg: 1,
    nome: 'TJPB',
    descricao: 'D.O. PARAIBA - TRIBUNAL DE JUSTIÇA',
  },
  {
    id: 96,
    idUF: 15,
    idTribCateg: 1,
    nome: 'TJPB',
    descricao: 'D.O. PARAIBA - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 98,
    idUF: 15,
    idTribCateg: 2,
    nome: 'TREPB',
    descricao: 'DJE TRE - PB',
  },
  {
    id: 99,
    idUF: 15,
    idTribCateg: 3,
    nome: 'JFPB',
    descricao: 'D.O. Paraíba - SEC JUD FEDERAL',
  },
  {
    id: 99,
    idUF: 15,
    idTribCateg: 3,
    nome: 'JFPB',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 100,
    idUF: 15,
    idTribCateg: 4,
    nome: 'TRT09',
    descricao: 'D.O. PARAIBA - TRT',
  },

  {
    id: 101,
    idUF: 16,
    idTribCateg: 1,
    nome: 'TJPR',
    descricao: 'D.O. PARANA - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 102,
    idUF: 16,
    idTribCateg: 1,
    nome: 'TJPR',
    descricao: 'DJE TJ PR - PARTE 1',
  },
  {
    id: 103,
    idUF: 16,
    idTribCateg: 1,
    nome: 'TJPR',
    descricao: 'DJE TJ PR - PARTE 2',
  },
  {
    id: 104,
    idUF: 16,
    idTribCateg: 2,
    nome: 'TREPR',
    descricao: 'DJE TRE - PR',
  },
  {
    id: 105,
    idUF: 16,
    idTribCateg: 3,
    nome: 'JFPR',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 106,
    idUF: 16,
    idTribCateg: 4,
    nome: 'TRT26',
    descricao: 'D.O. PARANA - TRT',
  },

  {
    id: 107,
    idUF: 17,
    idTribCateg: 1,
    nome: 'TJPE',
    descricao: 'D.O. PERNAMBUCO - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 108,
    idUF: 17,
    idTribCateg: 1,
    nome: 'TJPE',
    descricao: 'DJE TJ PE - PARTE 1',
  },
  {
    id: 109,
    idUF: 17,
    idTribCateg: 1,
    nome: 'TJPE',
    descricao: 'DJE TJ PE - PARTE 2',
  },
  {
    id: 110,
    idUF: 17,
    idTribCateg: 2,
    nome: 'TREPE',
    descricao: 'DJE TRE - PE',
  },
  {
    id: 111,
    idUF: 17,
    idTribCateg: 3,
    nome: 'JFPE',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 112,
    idUF: 17,
    idTribCateg: 4,
    nome: 'TRT27',
    descricao: 'D.O. PERNAMBUCO - TRT',
  },

  {
    id: 113,
    idUF: 18,
    idTribCateg: 1,
    nome: 'TJPI',
    descricao: 'D.O. PIAUI - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 114,
    idUF: 18,
    idTribCateg: 1,
    nome: 'TJPI',
    descricao: 'DJE TJ PI - PARTE 1',
  },
  {
    id: 115,
    idUF: 18,
    idTribCateg: 1,
    nome: 'TJPI',
    descricao: 'DJE TJ PI - PARTE 2',
  },
  {
    id: 116,
    idUF: 18,
    idTribCateg: 2,
    nome: 'TREPI',
    descricao: 'DJE TRE - PI',
  },
  {
    id: 117,
    idUF: 18,
    idTribCateg: 3,
    nome: 'JFPI',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 118,
    idUF: 18,
    idTribCateg: 4,
    nome: 'TRT28',
    descricao: 'D.O. PIAUI - TRT',
  },

  {
    id: 119,
    idUF: 19,
    idTribCateg: 1,
    nome: 'TJRJ',
    descricao: 'D.O. RJ Cad 1 Administrativo',
  },
  {
    id: 120,
    idUF: 19,
    idTribCateg: 1,
    nome: 'TJRJ',
    descricao: 'D.O. RJ Cad 2 Jud 2 Instancia',
  },
  {
    id: 121,
    idUF: 19,
    idTribCateg: 1,
    nome: 'TJRJ',
    descricao: 'D.O. RJ Cad 3 Jud 1 Instancia Capital',
  },
  {
    id: 121,
    idUF: 19,
    idTribCateg: 1,
    nome: 'TJRJ',
    descricao: 'D.O. RJ Cad 4 Jud 1 Instancia Interior',
  },
  {
    id: 122,
    idUF: 19,
    idTribCateg: 1,
    nome: 'TJRJ',
    descricao: 'D.O. RJ Cad 5 Editais',
  },
  {
    id: 123,
    idUF: 19,
    idTribCateg: 2,
    nome: 'TRERJ',
    descricao: 'DJE TRE - RJ',
  },
  {
    id: 123,
    idUF: 19,
    idTribCateg: 3,
    nome: 'JFRJ',
    descricao: 'TRF DA 2 REG (DJEN)',
  },
  {
    id: 124,
    idUF: 19,
    idTribCateg: 4,
    nome: 'TRT01',
    descricao: 'D. O. RJ TRT - JT',
  },

  {
    id: 125,
    idUF: 24,
    idTribCateg: 1,
    nome: 'TJSC',
    descricao: 'D.O. SANTA CATARINA - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 126,
    idUF: 24,
    idTribCateg: 1,
    nome: 'TJSC',
    descricao: 'D.O. SANTA CATARINA JUSTICA ESTADUAL - Caderno Administrativo do Poder Judiciário',
  },
  {
    id: 127,
    idUF: 24,
    idTribCateg: 1,
    nome: 'TJSC',
    descricao: 'D.O. SANTA CATARINA JUSTICA ESTADUAL - Caderno Jurisdicional do Tribunal de Justiça',
  },
  {
    id: 128,
    idUF: 24,
    idTribCateg: 2,
    nome: 'TRESC',
    descricao: 'DJE TRE - SC',
  },
  {
    id: 129,
    idUF: 24,
    idTribCateg: 3,
    nome: 'JFSC',
    descricao: 'D.J.DF SEC II - TRF DA 4 REG',
  },
  {
    id: 130,
    idUF: 24,
    idTribCateg: 4,
    nome: 'TRT05',
    descricao: 'D.O. SANTA CATARINA - TRT',
  },

  {
    id: 131,
    idUF: 25,
    idTribCateg: 1,
    nome: 'TJSP',
    descricao: 'D.O. SAO PAULO - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 132,
    idUF: 25,
    idTribCateg: 1,
    nome: 'TJSP',
    descricao: 'DJE TJ SP - PARTE 1',
  },
  {
    id: 133,
    idUF: 25,
    idTribCateg: 1,
    nome: 'TJSP',
    descricao: 'DJE TJ SP - PARTE 2',
  },
  {
    id: 134,
    idUF: 25,
    idTribCateg: 2,
    nome: 'TRESSP',
    descricao: 'DJE TRE - SP',
  },
  {
    id: 135,
    idUF: 25,
    idTribCateg: 3,
    nome: 'JFSP',
    descricao: 'TRF DA 3 REG (DJEN)',
  },
  {
    id: 136,
    idUF: 25,
    idTribCateg: 4,
    nome: 'TRT02',
    descricao: 'D.O. SAO PAULO - TRT',
  },

  {
    id: 137,
    idUF: 27,
    idTribCateg: 1,
    nome: 'TJTO',
    descricao: 'D.O. Tocantins - TRIBUNAL DE JUSTIÇA (DJEN)',
  },
  {
    id: 138,
    idUF: 27,
    idTribCateg: 1,
    nome: 'TJTO',
    descricao: 'DJE TJ TO - PARTE 1',
  },
  {
    id: 139,
    idUF: 27,
    idTribCateg: 1,
    nome: 'TJTO',
    descricao: 'DJE TJ TO - PARTE 2',
  },
  {
    id: 140,
    idUF: 27,
    idTribCateg: 2,
    nome: 'TRETO',
    descricao: 'DJE TRE - TO',
  },
  {
    id: 141,
    idUF: 27,
    idTribCateg: 3,
    nome: 'JFTO',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 142,
    idUF: 27,
    idTribCateg: 4,
    nome: 'TRT15',
    descricao: 'D.O. Tocantins - TRT',
  },

  {
    id: 143,
    idUF: 20,
    idTribCateg: 1,
    nome: 'TJRN',
    descricao: 'D.O. Rio Grande do Norte - Administrativo',
  },
  {
    id: 144,
    idUF: 20,
    idTribCateg: 1,
    nome: 'TJRN',
    descricao: 'D.O. Rio Grande do Norte - Judiciais',
  },
  {
    id: 145,
    idUF: 20,
    idTribCateg: 2,
    nome: 'TRERN',
    descricao: 'DJE TRE - RN',
  },
  {
    id: 146,
    idUF: 20,
    idTribCateg: 3,
    nome: 'JFRN',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 147,
    idUF: 20,
    idTribCateg: 4,
    nome: 'TRT03',
    descricao: 'D.O. Rio Grande do Norte - TRT',
  },

  {
    id: 148,
    idUF: 21,
    idTribCateg: 1,
    nome: 'TJRS',
    descricao: 'D.O. Rio Grande do Sul - Administrativo',
  },
  {
    id: 149,
    idUF: 21,
    idTribCateg: 1,
    nome: 'TJRS',
    descricao: 'D.O. Rio Grande do Sul - Judiciais',
  },
  {
    id: 150,
    idUF: 21,
    idTribCateg: 2,
    nome: 'TRERS',
    descricao: 'DJE TRE - RS',
  },
  {
    id: 151,
    idUF: 21,
    idTribCateg: 3,
    nome: 'JFRS',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 152,
    idUF: 21,
    idTribCateg: 4,
    nome: 'TRT04',
    descricao: 'D.O. Rio Grande do Sul - TRT',
  },

  {
    id: 153,
    idUF: 22,
    idTribCateg: 1,
    nome: 'TJRO',
    descricao: 'D.O. Rondonia - Administrativo',
  },
  {
    id: 154,
    idUF: 22,
    idTribCateg: 1,
    nome: 'TJRO',
    descricao: 'D.O. Rondonia - Judiciais',
  },
  {
    id: 155,
    idUF: 22,
    idTribCateg: 2,
    nome: 'TRERO',
    descricao: 'DJE TRE - RO',
  },
  {
    id: 156,
    idUF: 22,
    idTribCateg: 3,
    nome: 'JFRO',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 157,
    idUF: 22,
    idTribCateg: 4,
    nome: 'TRT05',
    descricao: 'D.O. Rondonia - TRT',
  },

  {
    id: 158,
    idUF: 23,
    idTribCateg: 1,
    nome: 'TJRR',
    descricao: 'D.O. Roraima - Administrativo',
  },
  {
    id: 159,
    idUF: 23,
    idTribCateg: 1,
    nome: 'TJRR',
    descricao: 'D.O. Roraima - Judiciais',
  },
  {
    id: 160,
    idUF: 23,
    idTribCateg: 2,
    nome: 'TRERR',
    descricao: 'DJE TRE - RR',
  },
  {
    id: 161,
    idUF: 23,
    idTribCateg: 3,
    nome: 'JFRR',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 162,
    idUF: 23,
    idTribCateg: 4,
    nome: 'TRT06',
    descricao: 'D.O. Roraima - TRT',
  },

  {
    id: 163,
    idUF: 26,
    idTribCateg: 1,
    nome: 'TJSE',
    descricao: 'D.O. Sergipe - Administrativo',
  },
  {
    id: 164,
    idUF: 26,
    idTribCateg: 1,
    nome: 'TJSE',
    descricao: 'D.O. Sergipe - Judiciais',
  },
  {
    id: 165,
    idUF: 26,
    idTribCateg: 2,
    nome: 'TRERSE',
    descricao: 'DJE TRE - SE',
  },
  {
    id: 166,
    idUF: 26,
    idTribCateg: 3,
    nome: 'JFSE',
    descricao: 'TRF DA 1 REG (DJEN)',
  },
  {
    id: 167,
    idUF: 26,
    idTribCateg: 4,
    nome: 'TRT07',
    descricao: 'D.O. Sergipe - TRT',
  },
];

export const tipoRole = [
  { id: 1, value: 'Estagiário', label: 'Estagiário' },
  { id: 2, value: 'controlador', label: 'Controlador' },
  { id: 3, value: 'Gerente', label: 'Gerente' },
  { id: 4, value: 'administrador', label: 'Administrador' },
  { id: 5, value: 'correspondente', label: 'Correspondente' },
];

export const tipoServico = [
  { id: 1, value: 'Todos', label: 'Todos' },
  { id: 2, value: 'Diligências_Judiciais', label: 'Diligências Judiciais' },
  { id: 3, value: 'Diligências_ExtraJudiciais', label: 'Diligências Extrajdiciais' },
  { id: 4, value: 'Audiências_Judiciais', label: 'Audiências Judiciais' },
  { id: 5, value: 'Audiências_ExtraJudiciais', label: 'Audiências ExtraJudiciais' },
  { id: 6, value: 'Duo_Diligence', label: 'Due Diligence' },
];
